language: node_js
node_js:
- '4.0'
- '8.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: mail@djm.org.uk
    api_key:
      secure: 4idH51HRSj8b8L32OU7C6CUSLW1GUn7Qe4534upm0UcWakddRgiEqfc5PL/PN2vgC9elLhJaQBymQfHlwlOBXN6vDQyMYGIsWQpeOhKIr3bkPWUHhaL4+nGITReEPXhr6weIjzOIk4MMyhEAZZEacJHMHWm1IhaBzUEL6TxT1tcnlW83LeQNvbX9ys2ybPBXbS5a6g5ikS/PQDsSUIFL46Jq7T1NjsmVvdh5KXO1eo+oQHPCpbo1f+1e5rUuLOJXa5FNXgBPj2QEPcam7+N2/5pDXOI0q3qY2tBEyXdVGrsHmwwtHUDDHd22Y1spbf1F4Jt7YwLKiOUVQhJVQo3IaQhvVjmH+pmNaC1q/uWp2Zw4to+Lu3EqZ+WrfN7devYUU0FnMKFSzsc+bBFyv4anZgOBCVCCE64PiwzGm9iDCSToajF3DVzlRcewaJuIvl9KuKpMkXH8FnbENxk5laZ4MM9VbeSv4cduQQZQVeYJo9Io9/lj8EXmLuW9gAMNRI0VHtWAzwATkg2JioFbiNWIMoeczEgzXUmaNgRyBt0TrjMsiwDsKEsRf51Ppv7kHe7qPVMt8E5AlXYzykKhCQwxZx/t0d4Pwt+MnLiAOHCCq7CZJ9tiKq+7+4IMCC+3JnnHqldfVxRVVAEM5toh0MCPuxYxcQVA/Iup6Ix1k0BNCHI=
    on:
      tags: true
      node: '8.0'
